### ISSUE TITLE
Samba image not update since Samba v4.18.9

### ISSUE THREAD

**Issue by davidandreoletti** [unixfox/periodic-build-with-github-actions#22]
Hi @unixfox ,

I use your Samba docker image and noticed the samba docker image has not been updated since v4.18.9 despite [GitHub action running.](https://github.com/unixfox/periodic-build-with-github-actions/actions/runs/8959842948). Not sure if you are aware / care about this issue.

1. Do you still actively use this image ?
2. If yes, do you intend to fix/resume samba image updates by any chance ?

Regards,

David

**Comment by unixfox** [comment]
It's building the docker image from https://github.com/dperson/samba/blob/master/Dockerfile as specified in https://github.com/unixfox/periodic-build-with-github-actions/blob/master/.github/workflows/docker-build-samba.yml

Which means it's using samba from alpine linux latest stable version which is v4.18.9 like you said: https://pkgs.alpinelinux.org/packages?name=samba&branch=v3.19&repo=&arch=&maintainer=

Once alpine linux will have a new stable version, the samba version will be updated.
