### ISSUE TITLE
Huginn update?

### ISSUE THREAD

**Issue by relrod** [unixfox/periodic-build-with-github-actions#23]
Hey, thanks for your work on providing working ARM images for all these projects.

I am looking to deploy huginn in my homelab and need an ARM image for it. I saw you have one, but it looks like it hasn't updated since last year: https://quay.io/repository/unixfox/huginn-single-process?tab=tags

I was wondering if you were planning to get it building and updating again, or if there's a known issue maybe I could help try to solve? Happy to help in whatever way I can :)

**Comment by unixfox** [comment]
Huginn doesn't build correctly anymore, it fails on arm64.

Feel free to submit some changes, I don't have the time for that anymore.
