### ISSUE TITLE
Can't connect to local MySQL server through socket 

### ISSUE THREAD

**Issue by auspic7** [unixfox/periodic-build-with-github-actions#4]
When I try to start huginn service using docker compose, I get this error:

```
Can't connect to local MySQL server through socket '/app/tmp/sockets/mysqld.sock' (2)
Couldn't create 'huginn_production' database. Please check your configuration.
rake aborted!
Mysql2::Error::ConnectionError: Can't connect to local MySQL server through socket '/app/tmp/sockets/mysqld.sock' (2)
```

I suppose this error is related to database settings(e.g. env. var.) but I don't know how to set it. could you please give some instruction when integrating it with the database?

**Comment by unixfox** [comment]
Please read the documentation: https://github.com/huginn/huginn/tree/master/docker/single-process
